* GNU GRUB rescue image

This repo contains a Nix flake building grub-rescue image for both
legacy boot and EFI boot.  Clone this repo, then type:
#+begin_src sh
  cd REPO
  nix build
#+end_src

The resulting images can then be found in =result= directory.

* Rescue your NixOS on ZFS installation

The resulting image can be used to boot any operating system supported
by GRUB, including but not limited to FreeBSD, GNU/Linux, and
Micro$oft Windoze.

However, I'm only going to document how to boot NixOS on ZFS, since
I'm the author of [[https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS.html][that guide]] :-).

1. Build the Nix flake, or download the appropriate prebuilt image
   from [[https://github.com/ne9z/grub-rescue-flake/releases][this repo]].
2. Write the image to a disk and boot your computer from it.
3. Now NixOS boot menu should appear.

Although I’m not a GRUB fanatic like [[https://www.gnu.org/software/grub/manual/grub/html_node/Role-of-a-boot-loader.html][Gordon Matzigkeit]], I still
appreciate GNU GRUB as a well engineered piece of software. I don’t
really get the hate against it, which I’ve also encountered elsewhere
on the internet.
